"""
SurgGreen — Base de Connaissances Clinique & Éco v3.1
══════════════════════════════════════════════════════

DONNÉES ACV (CO₂) — Sources primaires
──────────────────────────────────────
• Ti-6Al-4V (CNC)  : 35–52 kg CO₂/kg  → Ecoinvent 3.9 / Priarone et al., J Ind Ecol 2017
• Ti-6Al-4V (SLM)  : 50–95 kg CO₂/kg  → Xiao et al. 2024
• Acier 316L        : 5.1 kg CO₂/kg    → Ecoinvent 3.9 "chromium steel 18/8 hot rolled RER"
• CoCrMo            : 48–58 kg CO₂/kg  → Cobalt ~97 kg/kg (Norgate 2004) × fraction
• PEEK              : 9.8 kg CO₂/kg    → PlasticsEurope Eco-profile high-perf polymers 2022
• UHMWPE crosslinked: 3.4 kg CO₂/kg   → PlasticsEurope HDPE proxy + irradiation
• PLA               : 2.2 kg CO₂/kg    → Ecoinvent 3.9 "polylactic acid granulate"
• HA                : 3.1 kg CO₂/kg    → Dorozhkin SV Acta Biomater 2010
• Zircone Y-TZP     : 12.8 kg CO₂/kg  → Energie calcination/frittage (Chevalier 2009)
• Tantale           : 152 kg CO₂/kg    → Norgate & Rankin Miner Eng 2002

DONNÉES TRANSPORT — Hypothèses de calcul
──────────────────────────────────────────
• Fret aérien       : 0.00050 kg CO₂/km/kg  (ICAO Carbon Estimator 2023)
• Fret maritime     : 0.00001 kg CO₂/km/kg  (IMO GHG Study 2020)
• Fret routier      : 0.00010 kg CO₂/km/kg  (ADEME Bilan Carbone 2023)
• Coût financier    : 0.0003 €/km/kg (aérien) ; 0.00003 €/km/kg (maritime) — estimations logistique médicale

Point de référence : Paris, France (lat 48.85, lon 2.35)
"""

# ─────────────────────────────────────────────────────────────────────────────
# DONNÉES ORIGINES & TRANSPORT
# ─────────────────────────────────────────────────────────────────────────────
# mode_transport : "aerien" | "maritime" | "routier"
# co2_par_km_par_kg : facteur d'émission selon mode
# cout_eur_par_km_par_kg : coût logistique estimé
TRANSPORT_FACTEURS = {
    "aerien":   {"co2": 0.00050, "cout": 0.00030},
    "maritime": {"co2": 0.00001, "cout": 0.000030},
    "routier":  {"co2": 0.00010, "cout": 0.000080},
}

# Origines géographiques par matériau
# lat/lon = coordonnées du principal centre de production
ORIGINES = {
    "titane_grade5": {
        "pays": "Japon / USA",
        "ville_ref": "Osaka",
        "lat": 34.69, "lon": 135.50,
        "distance_km": 9700,
        "mode_transport": "aerien",
        "note_origine": "Alliage Ti-6Al-4V — Sumitomo (JP), ATI Metals (USA)",
        "flag": "🇯🇵",
    },
    "titane_grade23": {
        "pays": "USA",
        "ville_ref": "Pittsburgh",
        "lat": 40.44, "lon": -79.99,
        "distance_km": 6700,
        "mode_transport": "aerien",
        "note_origine": "ATI Metals, Carpenter Technology — grade ELI certifié ASTM F136",
        "flag": "🇺🇸",
    },
    "titane_poreux_3d": {
        "pays": "Allemagne / Belgique",
        "ville_ref": "Bruxelles",
        "lat": 50.85, "lon": 4.35,
        "distance_km": 310,
        "mode_transport": "routier",
        "note_origine": "EOS GmbH (DE), Materialise (BE) — impression SLM Ti local",
        "flag": "🇩🇪",
    },
    "acier_316L": {
        "pays": "Allemagne",
        "ville_ref": "Düsseldorf",
        "lat": 51.22, "lon": 6.78,
        "distance_km": 490,
        "mode_transport": "routier",
        "note_origine": "Outokumpu, ThyssenKrupp — production européenne ISO 5832-1",
        "flag": "🇩🇪",
    },
    "cobalt_chrome": {
        "pays": "RDC → Belgique (raffiné)",
        "ville_ref": "Liège",
        "lat": 50.63, "lon": 5.57,
        "distance_km": 370,
        "mode_transport": "routier",
        "note_origine": "Minerai cobalt RDC → raffinerie Umicore (Hoboken, BE)",
        "flag": "🇧🇪",
    },
    "tantale_poreux": {
        "pays": "RDC / Rwanda → USA",
        "ville_ref": "Portland (OR)",
        "lat": 45.52, "lon": -122.67,
        "distance_km": 9200,
        "mode_transport": "aerien",
        "note_origine": "Coltan RDC/Rwanda → H.C. Starck (USA) → Zimmer Biomet",
        "flag": "🇺🇸",
    },
    "nitinol": {
        "pays": "USA",
        "ville_ref": "Fremont (CA)",
        "lat": 37.54, "lon": -121.98,
        "distance_km": 9100,
        "mode_transport": "aerien",
        "note_origine": "Nitinol Devices & Components, Fort Wayne Metals (USA)",
        "flag": "🇺🇸",
    },
    "magnesium_bio": {
        "pays": "Chine",
        "ville_ref": "Shanghai",
        "lat": 31.22, "lon": 121.47,
        "distance_km": 9200,
        "mode_transport": "maritime",
        "note_origine": "Synbone AG (CH) & Shengkai Innovations (CN) — alliage WE43",
        "flag": "🇨🇳",
    },
    "peek": {
        "pays": "Royaume-Uni",
        "ville_ref": "Thornton Cleveleys",
        "lat": 53.87, "lon": -3.02,
        "distance_km": 1050,
        "mode_transport": "routier",
        "note_origine": "Victrex plc — seul producteur mondial Victrex® 450G (UK)",
        "flag": "🇬🇧",
    },
    "peek_cf": {
        "pays": "Royaume-Uni / USA",
        "ville_ref": "Thornton Cleveleys",
        "lat": 53.87, "lon": -3.02,
        "distance_km": 1050,
        "mode_transport": "routier",
        "note_origine": "Victrex (UK) + fibres carbone Toray (JP) — composite CFR-PEEK",
        "flag": "🇬🇧",
    },
    "uhmwpe_vit_e": {
        "pays": "Pays-Bas",
        "ville_ref": "Geleen",
        "lat": 51.00, "lon": 5.83,
        "distance_km": 360,
        "mode_transport": "routier",
        "note_origine": "DSM Biomedical (NL) — GUR 1020/1050 + vitamine E Zimmer Biomet",
        "flag": "🇳🇱",
    },
    "pla_bio": {
        "pays": "Pays-Bas / USA",
        "ville_ref": "Rotterdam",
        "lat": 51.92, "lon": 4.47,
        "distance_km": 430,
        "mode_transport": "routier",
        "note_origine": "TotalEnergies Corbion (NL), NatureWorks (USA) — granulés PLA",
        "flag": "🇳🇱",
    },
    "plga_resorbable": {
        "pays": "USA / Belgique",
        "ville_ref": "Birmingham (AL)",
        "lat": 33.52, "lon": -86.80,
        "distance_km": 7800,
        "mode_transport": "aerien",
        "note_origine": "Evonik Biomaterials (DE/USA), Corbion (BE) — PLGA 75:25 médical",
        "flag": "🇺🇸",
    },
    "pmma_neuro": {
        "pays": "Allemagne",
        "ville_ref": "Darmstadt",
        "lat": 49.87, "lon": 8.65,
        "distance_km": 450,
        "mode_transport": "routier",
        "note_origine": "Heraeus Medical GmbH, Stryker DE — ciment PMMA ISO 5833",
        "flag": "🇩🇪",
    },
    "polyuretane_bio": {
        "pays": "USA",
        "ville_ref": "Berkeley (CA)",
        "lat": 37.87, "lon": -122.27,
        "distance_km": 9100,
        "mode_transport": "aerien",
        "note_origine": "DSM Biomedical / Polymer Technology Group — Biospan™",
        "flag": "🇺🇸",
    },
    "ptfe_expanded": {
        "pays": "USA",
        "ville_ref": "Flagstaff (AZ)",
        "lat": 35.19, "lon": -111.65,
        "distance_km": 9000,
        "mode_transport": "aerien",
        "note_origine": "W. L. Gore & Associates — ePTFE Gore-Tex® médical (USA)",
        "flag": "🇺🇸",
    },
    "silicone_medical": {
        "pays": "Allemagne / France",
        "ville_ref": "Lyon",
        "lat": 45.75, "lon": 4.83,
        "distance_km": 460,
        "mode_transport": "routier",
        "note_origine": "Wacker Chemie (DE), NuSil (FR) — silicone grade implant",
        "flag": "🇩🇪",
    },
    "hydroxyapatite": {
        "pays": "France / Belgique",
        "ville_ref": "Pessac",
        "lat": 44.80, "lon": -0.63,
        "distance_km": 580,
        "mode_transport": "routier",
        "note_origine": "Ceraver (FR), Cam Bioceramics (NL) — HA synthétique ISO 13779",
        "flag": "🇫🇷",
    },
    "alumine": {
        "pays": "Allemagne",
        "ville_ref": "Selb",
        "lat": 50.17, "lon": 12.13,
        "distance_km": 720,
        "mode_transport": "routier",
        "note_origine": "CeramTec GmbH — BIOLOX® forte, Selb (Allemagne)",
        "flag": "🇩🇪",
    },
    "alumine_zircone": {
        "pays": "Allemagne",
        "ville_ref": "Selb",
        "lat": 50.17, "lon": 12.13,
        "distance_km": 720,
        "mode_transport": "routier",
        "note_origine": "CeramTec GmbH — BIOLOX® delta, composite AMC (Allemagne)",
        "flag": "🇩🇪",
    },
    "zircone": {
        "pays": "Australie → Allemagne",
        "ville_ref": "Selb",
        "lat": 50.17, "lon": 12.13,
        "distance_km": 720,
        "mode_transport": "routier",
        "note_origine": "Minerai zircon Australie → CeramTec / Saint-Gobain ZirPro (DE)",
        "flag": "🇩🇪",
    },
    "tcp_beta": {
        "pays": "France",
        "ville_ref": "Caen",
        "lat": 49.18, "lon": -0.36,
        "distance_km": 240,
        "mode_transport": "routier",
        "note_origine": "Kasios (FR), Noraker (FR) — β-TCP substitut osseux local",
        "flag": "🇫🇷",
    },
    "bioglass": {
        "pays": "Finlande / USA",
        "ville_ref": "Tampere",
        "lat": 61.49, "lon": 23.76,
        "distance_km": 2800,
        "mode_transport": "routier",
        "note_origine": "BonAlive Biomaterials (FI), Mo-Sci Corp (USA) — Bioglass 45S5",
        "flag": "🇫🇮",
    },
    "os_allogene": {
        "pays": "France (banques d'os)",
        "ville_ref": "Paris",
        "lat": 48.85, "lon": 2.35,
        "distance_km": 0,
        "mode_transport": "routier",
        "note_origine": "Banques d'os hospitalières françaises — circuit court national",
        "flag": "🇫🇷",
    },
    "collagene_bovin": {
        "pays": "France / Brésil",
        "ville_ref": "São Paulo",
        "lat": -23.55, "lon": -46.63,
        "distance_km": 9400,
        "mode_transport": "maritime",
        "note_origine": "Symatese (FR), Integra (USA) — collagène bovin réticulé",
        "flag": "🇧🇷",
    },
    "acide_hyaluronique": {
        "pays": "France / Italie",
        "ville_ref": "Padoue",
        "lat": 45.40, "lon": 11.87,
        "distance_km": 850,
        "mode_transport": "routier",
        "note_origine": "Fidia Farmaceutici (IT), LCA (FR) — HA réticulé grade implant",
        "flag": "🇮🇹",
    },
    "xenogreffe_porcine": {
        "pays": "Italie / USA",
        "ville_ref": "Milan",
        "lat": 45.46, "lon": 9.19,
        "distance_km": 840,
        "mode_transport": "routier",
        "note_origine": "Sorin Group (IT), Edwards Lifesciences (USA) — péricarde porcin",
        "flag": "🇮🇹",
    },
    "pyrocarbone": {
        "pays": "France",
        "ville_ref": "Péronnas",
        "lat": 46.01, "lon": 5.22,
        "distance_km": 460,
        "mode_transport": "routier",
        "note_origine": "Carbone Lorraine / Helicoid (FR) — LTI PyC seul producteur EU",
        "flag": "🇫🇷",
    },
    "scaffold_pcl": {
        "pays": "Belgique / Singapour",
        "ville_ref": "Louvain",
        "lat": 50.87, "lon": 4.70,
        "distance_km": 280,
        "mode_transport": "routier",
        "note_origine": "Materialise (BE), EnvisionTEC — scaffold PCL impression 3D",
        "flag": "🇧🇪",
    },
    "dacron_polyester": {
        "pays": "USA / Allemagne",
        "ville_ref": "Flagstaff (AZ)",
        "lat": 35.19, "lon": -111.65,
        "distance_km": 9000,
        "mode_transport": "aerien",
        "note_origine": "Vascutek Terumo (USA/UK), JOTEC GmbH (DE) — Dacron tressé",
        "flag": "🇺🇸",
    },
}


def get_cout_transport(key: str, poids_kg: float = 0.1) -> dict:
    """
    Calcule le coût carbone et financier du transport pour un matériau donné.
    poids_kg : poids estimé de l'implant (défaut 100g = 0.1 kg)
    Retourne un dict avec co2_transport_kg, cout_transport_eur, distance_km, mode.
    """
    orig = ORIGINES.get(key, {})
    if not orig:
        return {"co2_transport_kg": 0, "cout_transport_eur": 0, "distance_km": 0, "mode": "—"}

    dist = orig["distance_km"]
    mode = orig["mode_transport"]
    facteurs = TRANSPORT_FACTEURS[mode]

    co2  = round(dist * poids_kg * facteurs["co2"], 4)
    cout = round(dist * poids_kg * facteurs["cout"], 4)

    return {
        "co2_transport_kg":  co2,
        "cout_transport_eur": cout,
        "distance_km": dist,
        "mode": mode,
    }


# ─────────────────────────────────────────────────────────────────────────────
# DICTIONNAIRE MATÉRIAUX
# ─────────────────────────────────────────────────────────────────────────────

MATERIAUX = {

    # ── MÉTAUX ───────────────────────────────────────────────────────────────

    "titane_grade5": {
        "nom": "Titane Grade 5 (Ti-6Al-4V CNC)",
        "categorie": "Métal",
        "co2_kg_par_kg": 42.0,
        "co2_range": [35.0, 52.0],
        "module_elastique_gpa": 110.0,
        "stress_shielding": 4,
        "recyclable": True,
        "biodegradable": False,
        "duree_vie_implant_ans": 25,
        "types_chirurgie": [
            "orthopédie", "traumatologie", "rachis", "dentaire",
            "genou", "hanche", "maxillo-facial", "neurochirurgie"
        ],
        "taux_succes_pct": 95,
        "taux_succes_source": "NJR 2024 + AOANJRR 2023 — tiges fémorales Ti",
        "biocompatibilite": 5,
        "resistance_mecanique": 5,
        "osteointegration": 5,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO", "rayonnement_gamma"],
        "norme_iso": "ISO 5832-3",
        "prix_relatif": 3,
        "disponibilite": 5,
        "risque_infection": 2,
        "risque_allergie": 1,
        "reference": "Priarone et al. J Ind Ecol 2017; NJR 21st Report 2024",
    },

    "titane_grade23": {
        "nom": "Titane Grade 23 (Ti-6Al-4V ELI)",
        "categorie": "Métal",
        "co2_kg_par_kg": 44.0,
        "co2_range": [37.0, 54.0],
        "module_elastique_gpa": 110.0,
        "stress_shielding": 4,
        "recyclable": True,
        "biodegradable": False,
        "duree_vie_implant_ans": 30,
        "types_chirurgie": ["orthopédie", "hanche", "genou", "rachis", "traumatologie", "neurochirurgie"],
        "taux_succes_pct": 97,
        "taux_succes_source": "ASTM F136; AOANJRR 2023 — faible taux de révision",
        "biocompatibilite": 5,
        "resistance_mecanique": 5,
        "osteointegration": 5,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO"],
        "norme_iso": "ASTM F136 / ISO 5832-3",
        "prix_relatif": 4,
        "disponibilite": 4,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "ASTM F136; NJR 21st Report 2024",
    },

    "titane_poreux_3d": {
        "nom": "Titane Poreux Imprimé 3D (SLM)",
        "categorie": "Métal",
        "co2_kg_par_kg": 68.0,
        "co2_range": [50.0, 95.0],
        "module_elastique_gpa": 55.0,
        "stress_shielding": 2,
        "recyclable": True,
        "biodegradable": False,
        "duree_vie_implant_ans": 25,
        "types_chirurgie": ["oncologie osseuse", "rachis", "hanche", "neurochirurgie", "reprise"],
        "taux_succes_pct": 93,
        "taux_succes_source": "Sing SL 2021 — revue implants SLM Ti; données cliniques encore limitées",
        "biocompatibilite": 5,
        "resistance_mecanique": 4,
        "osteointegration": 5,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["EtO", "rayonnement_gamma"],
        "norme_iso": "ISO 5832-3",
        "prix_relatif": 5,
        "disponibilite": 2,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Xiao et al. 2024 (CO2 SLM); Sing SL et al. 2021",
    },

    "acier_316L": {
        "nom": "Acier Inoxydable 316L",
        "categorie": "Métal",
        "co2_kg_par_kg": 5.1,
        "co2_range": [4.2, 7.5],
        "module_elastique_gpa": 200.0,
        "stress_shielding": 5,
        "recyclable": True,
        "biodegradable": False,
        "duree_vie_implant_ans": 10,
        "types_chirurgie": ["traumatologie", "fixation externe", "rachis"],
        "taux_succes_pct": 89,
        "taux_succes_source": "Usage temporaire — corrosion en milieu chloruré long terme",
        "biocompatibilite": 3,
        "resistance_mecanique": 5,
        "osteointegration": 2,
        "radio_opaque": True,
        "compatible_irm": False,
        "sterilisation": ["autoclave", "EtO"],
        "norme_iso": "ISO 5832-1",
        "prix_relatif": 1,
        "disponibilite": 5,
        "risque_infection": 3,
        "risque_allergie": 3,
        "reference": "Ecoinvent 3.9 'chromium steel 18/8 hot rolled RER'; Hedberg 2014",
    },

    "cobalt_chrome": {
        "nom": "Cobalt-Chrome (CoCrMo)",
        "categorie": "Métal",
        "co2_kg_par_kg": 51.0,
        "co2_range": [45.0, 58.0],
        "module_elastique_gpa": 225.0,
        "stress_shielding": 5,
        "recyclable": True,
        "biodegradable": False,
        "duree_vie_implant_ans": 20,
        "types_chirurgie": ["orthopédie", "hanche", "genou", "dentaire"],
        "taux_succes_pct": 94,
        "taux_succes_source": "NJR PLOS Med 2024 — CoCr/HXLPE: 94.7% survie 10 ans (1 026 481 hanches)",
        "biocompatibilite": 3,
        "resistance_mecanique": 5,
        "osteointegration": 3,
        "radio_opaque": True,
        "compatible_irm": False,
        "sterilisation": ["autoclave", "EtO"],
        "norme_iso": "ISO 5832-4 (coulé) / ISO 5832-12 (forgé)",
        "prix_relatif": 3,
        "disponibilite": 4,
        "risque_infection": 2,
        "risque_allergie": 4,
        "reference": "NJR PLOS Med 2024; Norgate 2004 (ACV cobalt); ScienceDirect 2024",
    },

    "tantale_poreux": {
        "nom": "Tantale Poreux (Trabecular Metal™)",
        "categorie": "Métal",
        "co2_kg_par_kg": 152.0,
        "co2_range": [120.0, 200.0],
        "module_elastique_gpa": 3.0,
        "stress_shielding": 1,
        "recyclable": True,
        "biodegradable": False,
        "duree_vie_implant_ans": 30,
        "types_chirurgie": ["oncologie osseuse", "reprise", "hanche", "genou"],
        "taux_succes_pct": 96,
        "taux_succes_source": "Levine B. J Am Acad Orthop Surg 2008 + séries Zimmer Biomet",
        "biocompatibilite": 5,
        "resistance_mecanique": 4,
        "osteointegration": 5,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ASTM F560",
        "prix_relatif": 5,
        "disponibilite": 2,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Levine B. J Am Acad Orthop Surg 2008; Norgate & Rankin Miner Eng 2002",
    },

    "nitinol": {
        "nom": "Nitinol NiTi (Superélastique)",
        "categorie": "Métal",
        "co2_kg_par_kg": 91.0,
        "co2_range": [70.0, 120.0],
        "module_elastique_gpa": 48.0,
        "stress_shielding": 2,
        "recyclable": True,
        "biodegradable": False,
        "duree_vie_implant_ans": 20,
        "types_chirurgie": ["rachis", "cardiovasculaire", "vasculaire"],
        "taux_succes_pct": 91,
        "taux_succes_source": "Morgan NB. Mater Sci Eng C 2004 — revue stents et agrafes NiTi",
        "biocompatibilite": 4,
        "resistance_mecanique": 4,
        "osteointegration": 2,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["EtO", "rayonnement_gamma"],
        "norme_iso": "ASTM F2063",
        "prix_relatif": 5,
        "disponibilite": 3,
        "risque_infection": 2,
        "risque_allergie": 3,
        "reference": "Morgan NB. Mater Sci Eng C 2004",
    },

    "magnesium_bio": {
        "nom": "Magnésium Bio-résorbable (WE43)",
        "categorie": "Métal",
        "co2_kg_par_kg": 18.5,
        "co2_range": [12.0, 26.0],
        "module_elastique_gpa": 45.0,
        "stress_shielding": 2,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 2,
        "types_chirurgie": ["pédiatrie", "traumatologie", "main", "orthopédie"],
        "taux_succes_pct": 87,
        "taux_succes_source": "Zhao D. Biomaterials 2017 — revue Mg biodégradable",
        "biocompatibilite": 4,
        "resistance_mecanique": 3,
        "osteointegration": 4,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ASTM F3094 (en cours)",
        "prix_relatif": 4,
        "disponibilite": 2,
        "risque_infection": 2,
        "risque_allergie": 1,
        "reference": "Zhao D. Biomaterials 2017",
    },

    # ── POLYMÈRES ────────────────────────────────────────────────────────────

    "peek": {
        "nom": "PEEK Standard (Victrex® 450G)",
        "categorie": "Polymère",
        "co2_kg_par_kg": 9.8,
        "co2_range": [7.5, 13.0],
        "module_elastique_gpa": 3.6,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 25,
        "types_chirurgie": ["rachis", "neurochirurgie", "maxillo-facial"],
        "taux_succes_pct": 93,
        "taux_succes_source": "Kurtz SM & Devine JN. Biomaterials 2007 — usage rachis >10 ans",
        "biocompatibilite": 5,
        "resistance_mecanique": 4,
        "osteointegration": 2,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO", "rayonnement_gamma"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 4,
        "disponibilite": 4,
        "risque_infection": 2,
        "risque_allergie": 1,
        "reference": "Kurtz SM & Devine JN. Biomaterials 2007; PlasticsEurope 2022",
    },

    "peek_cf": {
        "nom": "PEEK Fibres Carbone (CFR-PEEK)",
        "categorie": "Composite",
        "co2_kg_par_kg": 29.0,
        "co2_range": [22.0, 38.0],
        "module_elastique_gpa": 18.0,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 25,
        "types_chirurgie": ["oncologie osseuse", "rachis", "neurochirurgie"],
        "taux_succes_pct": 94,
        "taux_succes_source": "Duflou JR. CIRP Annals 2012; séries cliniques rachis",
        "biocompatibilite": 5,
        "resistance_mecanique": 5,
        "osteointegration": 2,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 5,
        "disponibilite": 3,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Duflou JR CIRP 2012; PMC7760052 (module élastique)",
    },

    "uhmwpe_vit_e": {
        "nom": "UHMWPE Réticulé + Vitamine E",
        "categorie": "Polymère",
        "co2_kg_par_kg": 3.4,
        "co2_range": [2.8, 4.5],
        "module_elastique_gpa": 0.8,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 20,
        "types_chirurgie": ["orthopédie", "genou", "hanche"],
        "taux_succes_pct": 96,
        "taux_succes_source": "NJR 2024 Partridge — CoCr/HXLPE 550 658 TKA; meilleure survie polymère",
        "biocompatibilite": 5,
        "resistance_mecanique": 3,
        "osteointegration": 1,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["rayonnement_gamma", "EtO"],
        "norme_iso": "ISO 5834-1 / ISO 5834-2",
        "prix_relatif": 3,
        "disponibilite": 5,
        "risque_infection": 2,
        "risque_allergie": 1,
        "reference": "Kurtz SM UHMWPE Handbook 2016; NJR Partridge JBJS 2020",
    },

    "pla_bio": {
        "nom": "PLA Biosourcé (Acide Polylactique)",
        "categorie": "Polymère",
        "co2_kg_par_kg": 2.2,
        "co2_range": [1.4, 3.0],
        "module_elastique_gpa": 3.5,
        "stress_shielding": 1,
        "recyclable": True,
        "biodegradable": True,
        "duree_vie_implant_ans": 2,
        "types_chirurgie": ["pédiatrie", "main", "maxillo-facial", "ophtalmologie"],
        "taux_succes_pct": 87,
        "taux_succes_source": "Vink E. Polym Degrad Stab 2004; études cliniques maxillo-facial",
        "biocompatibilite": 4,
        "resistance_mecanique": 2,
        "osteointegration": 3,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ISO 13781",
        "prix_relatif": 2,
        "disponibilite": 4,
        "risque_infection": 2,
        "risque_allergie": 2,
        "reference": "Vink E. Polym Degrad Stab 2004; Ecoinvent 3.9 PLA granulate",
    },

    "plga_resorbable": {
        "nom": "PLGA 75:25 (Copolymère Résorbable)",
        "categorie": "Polymère",
        "co2_kg_par_kg": 3.0,
        "co2_range": [2.2, 4.0],
        "module_elastique_gpa": 2.0,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 1,
        "types_chirurgie": ["pédiatrie", "traumatologie", "ophtalmologie", "main"],
        "taux_succes_pct": 85,
        "taux_succes_source": "Athanasiou KA. Biomaterials 1996 — vis et broches PLGA",
        "biocompatibilite": 4,
        "resistance_mecanique": 2,
        "osteointegration": 3,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 3,
        "disponibilite": 4,
        "risque_infection": 2,
        "risque_allergie": 2,
        "reference": "Athanasiou KA. Biomaterials 1996",
    },

    "pmma_neuro": {
        "nom": "PMMA Chirurgical (Ciment Acrylique)",
        "categorie": "Polymère",
        "co2_kg_par_kg": 4.5,
        "co2_range": [3.2, 6.0],
        "module_elastique_gpa": 2.5,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 15,
        "types_chirurgie": ["neurochirurgie", "rachis", "cranioplastie"],
        "taux_succes_pct": 88,
        "taux_succes_source": "Kühn KD. Bone Cement 2000; vertébroplastie",
        "biocompatibilite": 3,
        "resistance_mecanique": 3,
        "osteointegration": 1,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ISO 5833",
        "prix_relatif": 2,
        "disponibilite": 5,
        "risque_infection": 3,
        "risque_allergie": 2,
        "reference": "Kühn KD. Bone Cement 2000",
    },

    "polyuretane_bio": {
        "nom": "Polyuréthane Biostable (Biospan™)",
        "categorie": "Polymère",
        "co2_kg_par_kg": 5.5,
        "co2_range": [4.0, 7.5],
        "module_elastique_gpa": 0.05,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 15,
        "types_chirurgie": ["cardiovasculaire", "vasculaire", "reconstruction"],
        "taux_succes_pct": 88,
        "taux_succes_source": "Zdrahala RJ. J Biomater Appl 1999",
        "biocompatibilite": 4,
        "resistance_mecanique": 3,
        "osteointegration": 1,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 3,
        "disponibilite": 3,
        "risque_infection": 2,
        "risque_allergie": 2,
        "reference": "Zdrahala RJ. J Biomater Appl 1999",
    },

    "ptfe_expanded": {
        "nom": "ePTFE Gore-Tex® Expanded",
        "categorie": "Polymère",
        "co2_kg_par_kg": 9.1,
        "co2_range": [7.0, 12.0],
        "module_elastique_gpa": 0.1,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 20,
        "types_chirurgie": ["cardiovasculaire", "vasculaire", "reconstruction"],
        "taux_succes_pct": 91,
        "taux_succes_source": "Sefton MV. Ann NY Acad Sci 2002 — greffons vasculaires ePTFE",
        "biocompatibilite": 5,
        "resistance_mecanique": 3,
        "osteointegration": 1,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO", "rayonnement_gamma"],
        "norme_iso": "ISO 7198",
        "prix_relatif": 4,
        "disponibilite": 4,
        "risque_infection": 2,
        "risque_allergie": 1,
        "reference": "Sefton MV 2002; Ecoinvent 3.9 PTFE proxy",
    },

    "silicone_medical": {
        "nom": "Silicone Médical Grade Implant",
        "categorie": "Polymère",
        "co2_kg_par_kg": 6.2,
        "co2_range": [4.5, 8.5],
        "module_elastique_gpa": 0.002,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 15,
        "types_chirurgie": ["reconstruction", "main", "ophtalmologie", "maxillo-facial"],
        "taux_succes_pct": 88,
        "taux_succes_source": "Ratner BD. Biomaterials Science 2004",
        "biocompatibilite": 4,
        "resistance_mecanique": 2,
        "osteointegration": 1,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 3,
        "disponibilite": 5,
        "risque_infection": 2,
        "risque_allergie": 2,
        "reference": "Ratner BD. Biomaterials Science 2004",
    },

    # ── CÉRAMIQUES ───────────────────────────────────────────────────────────

    "hydroxyapatite": {
        "nom": "Hydroxyapatite Synthétique (HA)",
        "categorie": "Céramique",
        "co2_kg_par_kg": 3.1,
        "co2_range": [2.0, 5.0],
        "module_elastique_gpa": 80.0,
        "stress_shielding": 3,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 10,
        "types_chirurgie": ["dentaire", "orthopédie", "rachis", "maxillo-facial"],
        "taux_succes_pct": 89,
        "taux_succes_source": "Dorozhkin SV. Acta Biomater 2010 — revue systématique HA implants",
        "biocompatibilite": 5,
        "resistance_mecanique": 2,
        "osteointegration": 5,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "rayonnement_gamma"],
        "norme_iso": "ISO 13779",
        "prix_relatif": 2,
        "disponibilite": 4,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Dorozhkin SV. Acta Biomater 2010",
    },

    "alumine": {
        "nom": "Alumine Al₂O₃ (BIOLOX® forte)",
        "categorie": "Céramique",
        "co2_kg_par_kg": 8.5,
        "co2_range": [6.0, 11.0],
        "module_elastique_gpa": 380.0,
        "stress_shielding": 5,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 25,
        "types_chirurgie": ["orthopédie", "hanche", "genou"],
        "taux_succes_pct": 96,
        "taux_succes_source": "NJR PLOS Med 2024 — céramique/HXLPE: 96.4% survie 10 ans hanche",
        "biocompatibilite": 5,
        "resistance_mecanique": 4,
        "osteointegration": 2,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["autoclave"],
        "norme_iso": "ISO 6474-1",
        "prix_relatif": 4,
        "disponibilite": 3,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Chevalier J. Biomaterials 2006; NJR PLOS Med 2024",
    },

    "alumine_zircone": {
        "nom": "Composite AMC Alumine-Zircone (BIOLOX® delta)",
        "categorie": "Céramique",
        "co2_kg_par_kg": 10.5,
        "co2_range": [8.0, 14.0],
        "module_elastique_gpa": 350.0,
        "stress_shielding": 5,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 30,
        "types_chirurgie": ["hanche", "genou", "orthopédie"],
        "taux_succes_pct": 97,
        "taux_succes_source": "NJR PLOS Med 2024 — delta céramique/HXLPE: 97.1% survie 10 ans hanche",
        "biocompatibilite": 5,
        "resistance_mecanique": 5,
        "osteointegration": 2,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["autoclave"],
        "norme_iso": "ISO 6474-2",
        "prix_relatif": 5,
        "disponibilite": 2,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "NJR PLOS Med 2024 — delta ceramic hanche (gold standard 2024)",
    },

    "zircone": {
        "nom": "Zircone Y-TZP (Stabilisée Yttrium)",
        "categorie": "Céramique",
        "co2_kg_par_kg": 12.8,
        "co2_range": [9.0, 17.0],
        "module_elastique_gpa": 200.0,
        "stress_shielding": 4,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 25,
        "types_chirurgie": ["dentaire", "hanche", "ophtalmologie"],
        "taux_succes_pct": 94,
        "taux_succes_source": "Piconi C. Biomaterials 1999 — revue Y-TZP implants",
        "biocompatibilite": 5,
        "resistance_mecanique": 5,
        "osteointegration": 3,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["autoclave"],
        "norme_iso": "ISO 13356",
        "prix_relatif": 4,
        "disponibilite": 3,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Piconi C. Biomaterials 1999",
    },

    "tcp_beta": {
        "nom": "β-TCP (Phosphate Tricalcique Bêta)",
        "categorie": "Céramique",
        "co2_kg_par_kg": 2.8,
        "co2_range": [1.8, 4.0],
        "module_elastique_gpa": 33.0,
        "stress_shielding": 2,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 2,
        "types_chirurgie": ["dentaire", "maxillo-facial", "orthopédie"],
        "taux_succes_pct": 86,
        "taux_succes_source": "Bohner M. Injury 2000 — granules CaP clinique",
        "biocompatibilite": 5,
        "resistance_mecanique": 1,
        "osteointegration": 5,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "rayonnement_gamma"],
        "norme_iso": "ISO 13779",
        "prix_relatif": 2,
        "disponibilite": 4,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Bohner M. Injury 2000",
    },

    "bioglass": {
        "nom": "Bioglass 45S5 (Verre Bioactif)",
        "categorie": "Céramique",
        "co2_kg_par_kg": 4.2,
        "co2_range": [3.0, 6.0],
        "module_elastique_gpa": 35.0,
        "stress_shielding": 2,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 3,
        "types_chirurgie": ["ORL", "dentaire", "reconstruction", "maxillo-facial"],
        "taux_succes_pct": 84,
        "taux_succes_source": "Hench LL. Science 1984 — implants cochléaires, ORL",
        "biocompatibilite": 5,
        "resistance_mecanique": 1,
        "osteointegration": 5,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 3,
        "disponibilite": 3,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Hench LL. Science 1984",
    },

    # ── BIOSOURCÉS ───────────────────────────────────────────────────────────

    "os_allogene": {
        "nom": "Os Allogène Humain (Banque d'Os)",
        "categorie": "Biosourcé",
        "co2_kg_par_kg": 1.8,
        "co2_range": [0.8, 3.5],
        "module_elastique_gpa": 18.0,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 5,
        "types_chirurgie": ["oncologie osseuse", "rachis", "orthopédie"],
        "taux_succes_pct": 80,
        "taux_succes_source": "Vavken P. JBJS Am 2010 — révision allogreffe vs autogreffe",
        "biocompatibilite": 4,
        "resistance_mecanique": 3,
        "osteointegration": 5,
        "radio_opaque": True,
        "compatible_irm": True,
        "sterilisation": ["lyophilisation", "rayonnement_gamma"],
        "norme_iso": "ISO 12891",
        "prix_relatif": 3,
        "disponibilite": 2,
        "risque_infection": 4,
        "risque_allergie": 3,
        "reference": "Vavken P. JBJS Am 2010",
    },

    "collagene_bovin": {
        "nom": "Collagène Bovin Réticulé",
        "categorie": "Biosourcé",
        "co2_kg_par_kg": 2.5,
        "co2_range": [1.5, 4.0],
        "module_elastique_gpa": 0.5,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 1,
        "types_chirurgie": ["reconstruction", "ophtalmologie", "maxillo-facial"],
        "taux_succes_pct": 86,
        "taux_succes_source": "Lee CH. J Biomed Mater Res 2001",
        "biocompatibilite": 5,
        "resistance_mecanique": 1,
        "osteointegration": 3,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ISO 11979",
        "prix_relatif": 3,
        "disponibilite": 4,
        "risque_infection": 2,
        "risque_allergie": 3,
        "reference": "Lee CH. J Biomed Mater Res 2001",
    },

    "acide_hyaluronique": {
        "nom": "Acide Hyaluronique Réticulé (HA-XL)",
        "categorie": "Biosourcé",
        "co2_kg_par_kg": 1.5,
        "co2_range": [0.8, 2.5],
        "module_elastique_gpa": 0.001,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 1,
        "types_chirurgie": ["ophtalmologie", "reconstruction"],
        "taux_succes_pct": 91,
        "taux_succes_source": "Prestwich GD. J Control Release 2011",
        "biocompatibilite": 5,
        "resistance_mecanique": 1,
        "osteointegration": 1,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave"],
        "norme_iso": "ISO 11979",
        "prix_relatif": 4,
        "disponibilite": 4,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Prestwich GD. J Control Release 2011",
    },

    "xenogreffe_porcine": {
        "nom": "Xénogreffe Porcine Décellularisée",
        "categorie": "Biosourcé",
        "co2_kg_par_kg": 3.2,
        "co2_range": [2.0, 5.0],
        "module_elastique_gpa": 0.05,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 10,
        "types_chirurgie": ["cardiovasculaire", "reconstruction"],
        "taux_succes_pct": 87,
        "taux_succes_source": "Naso F. Sci Rep 2016 — péricarde porcin valve cardiaque",
        "biocompatibilite": 4,
        "resistance_mecanique": 2,
        "osteointegration": 2,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 3,
        "disponibilite": 3,
        "risque_infection": 2,
        "risque_allergie": 3,
        "reference": "Naso F. Sci Rep 2016",
    },

    # ── COMPOSITES & AVANCÉS ─────────────────────────────────────────────────

    "pyrocarbone": {
        "nom": "Pyrocarbone (LTI PyC)",
        "categorie": "Composite",
        "co2_kg_par_kg": 25.0,
        "co2_range": [18.0, 35.0],
        "module_elastique_gpa": 28.0,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 15,
        "types_chirurgie": ["main", "orthopédie", "cardiovasculaire"],
        "taux_succes_pct": 90,
        "taux_succes_source": "Cook SD. Clin Orthop 1992 — implants main PyC",
        "biocompatibilite": 5,
        "resistance_mecanique": 4,
        "osteointegration": 3,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 4,
        "disponibilite": 2,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Cook SD. Clin Orthop 1992",
    },

    "scaffold_pcl": {
        "nom": "Scaffold PCL Imprimé 3D (Polycaprolactone)",
        "categorie": "Composite",
        "co2_kg_par_kg": 3.3,
        "co2_range": [2.2, 5.0],
        "module_elastique_gpa": 0.4,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": True,
        "duree_vie_implant_ans": 3,
        "types_chirurgie": ["reconstruction", "pédiatrie", "maxillo-facial"],
        "taux_succes_pct": 85,
        "taux_succes_source": "Woodruff MA. Prog Polym Sci 2010",
        "biocompatibilite": 5,
        "resistance_mecanique": 2,
        "osteointegration": 3,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["EtO"],
        "norme_iso": "ISO 10993",
        "prix_relatif": 3,
        "disponibilite": 3,
        "risque_infection": 1,
        "risque_allergie": 1,
        "reference": "Woodruff MA. Prog Polym Sci 2010",
    },

    "dacron_polyester": {
        "nom": "Dacron Polyester Tressé (Woven PET)",
        "categorie": "Composite",
        "co2_kg_par_kg": 5.8,
        "co2_range": [4.5, 7.5],
        "module_elastique_gpa": 2.0,
        "stress_shielding": 1,
        "recyclable": False,
        "biodegradable": False,
        "duree_vie_implant_ans": 20,
        "types_chirurgie": ["cardiovasculaire", "vasculaire", "reconstruction"],
        "taux_succes_pct": 90,
        "taux_succes_source": "Kannan RY. J Biomed Mater Res B 2005 — greffons vasculaires 10 ans",
        "biocompatibilite": 4,
        "resistance_mecanique": 4,
        "osteointegration": 1,
        "radio_opaque": False,
        "compatible_irm": True,
        "sterilisation": ["autoclave", "EtO"],
        "norme_iso": "ISO 7198",
        "prix_relatif": 2,
        "disponibilite": 5,
        "risque_infection": 2,
        "risque_allergie": 2,
        "reference": "Kannan RY. J Biomed Mater Res B 2005",
    },
}


# ── NLP PATHOLOGIES ────────────────────────────────────────────────────────────
PATHO_KEYWORDS = {
    "oncologie osseuse":  ["cancer", "tumeur", "oncologie", "sarcome", "métastase", "ostéosarcome", "résection"],
    "pédiatrie":          ["enfant", "pédiatrie", "pédiatrique", "nourrisson", "adolescent", "croissance"],
    "rachis":             ["rachis", "vertèbre", "scoliose", "lombaire", "cervical", "discal", "dos", "colonne", "hernie"],
    "traumatologie":      ["fracture", "traumatologie", "fixation", "cassure", "choc", "ostéosynthèse", "plaque", "vis"],
    "dentaire":           ["dent", "dentaire", "implant dentaire", "couronne", "bridge", "alvéolaire"],
    "maxillo-facial":     ["mâchoire", "maxillaire", "facial", "mandibule", "visage", "crânien", "orbite"],
    "hanche":             ["hanche", "prothèse hanche", "col du fémur", "fémur proximal", "arthroplastie hanche"],
    "genou":              ["genou", "prothèse genou", "ligament croisé", "ménisque", "rotule", "arthroplastie genou"],
    "main":               ["main", "doigt", "poignet", "carpe", "métacarpe", "phalange", "tunnel carpien"],
    "orthopédie":         ["orthopédie", "articulaire", "articulation", "os long"],
    "neurochirurgie":     ["neuro", "neurochirurgie", "crâne", "cerveau", "cranio", "cranioplastie", "dure-mère"],
    "cardiovasculaire":   ["coeur", "cardiaque", "valve", "aorte", "coronaire", "cardiovasculaire", "pontage"],
    "vasculaire":         ["artère", "veine", "vasculaire", "stent", "endoprothèse", "by-pass", "ischémie"],
    "ophtalmologie":      ["oeil", "yeux", "ophtalmologie", "rétine", "cornée", "cristallin", "glaucome"],
    "reconstruction":     ["reconstruction", "plastie", "greffe", "cicatrice", "lambeau", "tissu mou"],
    "ORL":                ["ORL", "oreille", "nez", "gorge", "tympan", "otorhino", "cochléaire"],
}


# ── FONCTIONS DE SCORING ───────────────────────────────────────────────────────

def score_clinique(m: dict) -> float:
    s = (
        (m["taux_succes_pct"] / 100) * 3.5
        + (m["biocompatibilite"] / 5)  * 2.5
        + (m["osteointegration"] / 5)  * 2.0
        - (m["risque_infection"] / 5)  * 1.0
        - (m["risque_allergie"]  / 5)  * 1.0
    )
    return round(min(max(s, 0.0), 10.0), 2)


def score_environnemental(m: dict) -> float:
    co2 = m["co2_kg_par_kg"]
    if co2 <= 2:
        base = 9.5
    elif co2 <= 5:
        base = 9.0 - ((co2 - 2) / 3) * 2.0
    elif co2 <= 15:
        base = 7.0 - ((co2 - 5) / 10) * 3.0
    elif co2 <= 50:
        base = 4.0 - ((co2 - 15) / 35) * 3.0
    else:
        base = max(0.3, 1.0 - ((co2 - 50) / 150))

    if m["biodegradable"]:  base += 1.5
    if m.get("recyclable"): base += 0.5
    return round(min(base, 10.0), 2)


def score_stress_shielding(m: dict) -> float:
    gpa = m.get("module_elastique_gpa", 100.0)
    ratio = abs(gpa - 20.0) / 20.0
    s = max(0.0, 10.0 - ratio * 2.0)
    return round(min(s, 10.0), 2)


def score_global(m: dict) -> float:
    return round(
        score_clinique(m)               * 0.40
        + score_environnemental(m)      * 0.25
        + (m["taux_succes_pct"] / 10)   * 0.20
        + (m["disponibilite"] / 5 * 10) * 0.10
        + score_stress_shielding(m)     * 0.05,
        2,
    )
